//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public Lop()
        {
            this.PhieuSuDungSaches = new HashSet<PhieuSuDungSach>();
        }
    
        public int maLop { get; set; }
        public Nullable<int> maNamHoc { get; set; }
        public string tenLop { get; set; }
    
        public virtual NamHoc NamHoc { get; set; }
        public virtual ICollection<PhieuSuDungSach> PhieuSuDungSaches { get; set; }
    }
}
