//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTraSach
    {
        public string maSach { get; set; }
        public int maTinhTrangSach { get; set; }
        public Nullable<int> maTrangThai { get; set; }
        public System.DateTime ngayMuon { get; set; }
        public Nullable<System.DateTime> ngayDuKienTra { get; set; }
        public Nullable<System.DateTime> ngayTra { get; set; }
        public Nullable<int> tienPhat { get; set; }
        public string tenTrangThai { get; set; }
        public string tenTinhTrangSach { get; set; }
    }
}
