//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamHoc
    {
        public NamHoc()
        {
            this.Lops = new HashSet<Lop>();
        }
    
        public int maNamHoc { get; set; }
        public string tenNamHoc { get; set; }
    
        public virtual ICollection<Lop> Lops { get; set; }
    }
}
