//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiSuDung
    {
        public NguoiSuDung()
        {
            this.DangNhaps = new HashSet<DangNhap>();
            this.MuonSaches = new HashSet<MuonSach>();
            this.MuonSaches1 = new HashSet<MuonSach>();
        }
    
        public string maNguoiSD { get; set; }
        public string tenNguoiSD { get; set; }
    
        public virtual ICollection<DangNhap> DangNhaps { get; set; }
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
        public virtual ICollection<MuonSach> MuonSaches1 { get; set; }
    }
}
