//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSuDungSach
    {
        public PhieuSuDungSach()
        {
            this.MuonSaches = new HashSet<MuonSach>();
        }
    
        public string maPhieuSD { get; set; }
        public Nullable<int> maLop { get; set; }
        public string hoTen { get; set; }
        public Nullable<System.DateTime> ngayThangNamSinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string email { get; set; }
        public string soDT { get; set; }
    
        public virtual Lop Lop { get; set; }
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
    }
}
