//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraCuu
    {
        public string maSach { get; set; }
        public string tenSach { get; set; }
        public Nullable<int> namXB { get; set; }
        public Nullable<int> soTrang { get; set; }
        public Nullable<int> thoiHanMuon { get; set; }
        public Nullable<int> giaTien { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string tenLoaiSach { get; set; }
        public string tenTacGia { get; set; }
        public string tenNXB { get; set; }
        public string tenKhoSach { get; set; }
    }
}
