//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThai
    {
        public TrangThai()
        {
            this.MuonSaches = new HashSet<MuonSach>();
        }
    
        public int maTrangThai { get; set; }
        public string tenTrangThai { get; set; }
    
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
    }
}
