//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ThongKeSach
    {
        public string maSach { get; set; }
        public string tenSach { get; set; }
        public Nullable<int> maTacGia { get; set; }
        public string tenTacGia { get; set; }
        public string maLoaiSach { get; set; }
        public string tenLoaiSach { get; set; }
        public Nullable<int> maNXB { get; set; }
        public string tenNXB { get; set; }
        public Nullable<int> namXB { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> giaTien { get; set; }
        public Nullable<System.DateTime> ngayMuon { get; set; }
        public Nullable<int> maTrangThai { get; set; }
        public Nullable<int> tienPhat { get; set; }
        public Nullable<int> maTinhTrangSach { get; set; }
    }
}
