//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViTriLuuTru
    {
        public ViTriLuuTru()
        {
            this.LoaiSaches = new HashSet<LoaiSach>();
        }
    
        public int maViTriLuuTru { get; set; }
        public string tenViTriLuuTru { get; set; }
        public virtual ICollection<LoaiSach> LoaiSaches { get; set; }
    }
}
